### PR TITLE
CI first pass

### PR DESCRIPTION
**Pull request by jonocairns**
Adds github actions template that will run install and linting

https://github.com/jonocairns/Tdarr/pull/1/checks?check_run_id=300700574

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
Cheers.

Surprised you didn't have issues with Node 10. Meteor normally needs Node 8

**Comment by jonocairns** [comment]
> Surprised you didn't have issues with Node 10. Meteor normally needs Node 8

Ah yup, thats no problem, I can change that. I'm using node v10 locally and it's working fine, I am on windows though!

**Comment by HaveAGitGat** [comment]
Nice, will merge this once we sort out the scss PR

**Comment by HaveAGitGat** [comment]
Also Node 10 worked fine for me for the first day or 2 but then I started getting 'fibers' errors so downgraded.

**Pull request merged**
