### PR TITLE
Refactor navigation

### PR DESCRIPTION
**Pull request by jonocairns**
changes: https://recordit.co/4by4zhixmL

- Refactored the App.jsx file 
- Used `react-bootstrap` components for navigation
- Used react hooks to store basePath state (couldn't test this locally...)
- Removed unused styles

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
Hi Jono thanks for tidying that up! Really appreciate it. There are some nifty tricks in there that are new to me so I’ll review/understand this tomorrow (Saturday) and merge it.

**Comment by HaveAGitGat** [comment]
Also I’m trying to increase the render speed of all files when using the search tab. Currently it takes about 45 seconds for 7000 files. The react-tables [100k demo](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation?codemirror=1) only takes a few seconds so trying to work out why Tdarr takes so long. Any input would be very helpful.

**Comment by jonocairns** [comment]
Awesome 👍 I'm keen to help out in any way! I can take a look at the search this weekend :)

**Comment by jonocairns** [comment]
> 
> 
> Also I’m trying to increase the render speed of all files when using the search tab. Currently it takes about 45 seconds for 7000 files. The react-tables [100k demo](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation?codemirror=1) only takes a few seconds so trying to work out why Tdarr takes so long. Any input would be very helpful.

It looks like the default page size is too large -> https://github.com/tannerlinsley/react-table/issues/700#issuecomment-353682905 hints at the visible (page size) needs to be relatively low (maybe 5-10-20 per page). It can still sort and filter on the whole result set as it's mostly done virtually (without any render). I can chuck up a PR to adjust the page sizes if you'd like to test. I only have 20ish files in my test folder :P

**Pull request merged**
