### PR TITLE
Add Intel Arc hardware acceleration support.

### PR DESCRIPTION
**Pull request by Finn2708**
This PR addresses #902.

It updates Dockerfile.base to jammy and adds the latest media runtime (and probably some unrequired dependencies).
Unfortunately, I can't test Dockerfile.final, but in Dockerfile.base I can transcode with HandBreakCLI  using my Arc A380.

Let me know if I can assist with testing the final build.

### CODE REVIEW

**Comment by hollanbm** [comment]
> This PR addresses #902.
> 
> It updates Dockerfile.base to jammy and adds the latest media runtime (and probably some unrequired dependencies). Unfortunately, I can't test Dockerfile.final, but in Dockerfile.base I can transcode with HandBreakCLI using my Arc A380.
> 
> Let me know if I can assist with testing the final build.

While I'm generally a fan of all of the changes you made to the Dockerfile, the giant `RUN` commands make it harder to fully leverage the Docker layers cache.

I would instead open a second PR, with your refactors. It's hard to tell what is required for ARC, versus what isn't. Which could hold up the PR longer than is needed

**Comment by HaveAGitGat** [comment]
@Finn2708 thanks I'll try incorporating these changes.

@hollanbm as far as I'm aware it's better to use fewer `RUN` commands as each one creates a new layer which can dramatically increase image size depending on what's happening. So yes in development it's faster to use multiple `RUN` command so the layer cache can be used but not ideal for end image.

**Comment by HaveAGitGat** [comment]
But yes adding the RUN commands and changing the indenting does make it difficult to see exactly what has changed, I'll need to go through line by line.

**Comment by HaveAGitGat** [comment]
Kept the original formatting for now to make seeing the changes easier:

You can try changes with these images:

```
haveagitgat/tdarr_acc:dev_2.21.01_2024_06_14T12_07_12z
haveagitgat/tdarr_node_acc:dev_2.21.01_2024_06_14T12_07_12z
```

**Comment by HaveAGitGat** [comment]
Confirmed working ty.

**Comment by HaveAGitGat** [comment]
Just to add an example for this case, using separate Dockerfile `RUN` commands does increase image size a decent amount:

[Single RUN command (1.07GB)](https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev_2.21.01_2024_06_17T07_46_34z/images/sha256-8317b20ad228baaab75a26788c3c8766c07e2524ecf737f756d2f5f713d88dff?context=explore)

[Multiple RUN commands (1.25GB)](https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev_2.21.01_2024_06_17T08_08_44z/images/sha256-6950ef4568be313a10ec5cc9786eca7541276d992aa9f444a370d6793d55bcdd?context=explore)

**Comment by hollanbm** [comment]
> Just to add an example for this case, using separate Dockerfile `RUN` commands does increase image size a decent amount:
> 
> [Single RUN command (1.07GB)](https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev_2.21.01_2024_06_17T07_46_34z/images/sha256-8317b20ad228baaab75a26788c3c8766c07e2524ecf737f756d2f5f713d88dff?context=explore)
> 
> [Multiple RUN commands (1.25GB)](https://hub.docker.com/layers/haveagitgat/tdarr_acc/dev_2.21.01_2024_06_17T08_08_44z/images/sha256-6950ef4568be313a10ec5cc9786eca7541276d992aa9f444a370d6793d55bcdd?context=explore)

I went digging into this after we discussed above.

If you have command(s) that will add and then remove portions of what was added, it’s much better to use a single command. Otherwise the image size grows, as the first layer tracks the additions, and a second layer tracks the removals.

Outside of that, separate commands can leverage the cache more efficiently.

**Pull request merged**
