### PR TITLE
Eslint and fixes

### PR DESCRIPTION
**Pull request by jonocairns**
I know there are tones of changes in this PR but it's good to get linting done as early as possible!

- Added eslint and some base rules
- Added prettier to work with eslint to format code nicely
- Added linting step to package.json `npm run lint` and `npm run lint:fix`
- Added .vscode dir to recommend eslint extension so you can get before runtime errors (you can also get the auto fix functionality from pressing `ctrl + .`)
- Fixes some missing react key issues (https://reactjs.org/docs/lists-and-keys.html#keys) (we should probably make this a bit better than what I've done, but it's a start)

image

http://recordit.co/AuzF9Y3G01

https://recordit.co/7S1AYKIiN2

### CODE REVIEW

**Comment by HaveAGitGat** [comment]
Hi Jono thanks for this. Just having a test of it and there seem to be some issues, for example the plugins and logs tabs won't render as they are missing `import ReactDOM from 'react-dom';`

E.g. tab_Plugins.jsx before:

```
import React, { Component } from 'react';
import { withTracker } from 'meteor/react-meteor-data';
import ReactDOM from 'react-dom';
import { render } from 'react-dom';
import ReactTable from "react-table";

import { CopyToClipboard } from 'react-copy-to-clipboard';
import { Button } from 'react-bootstrap';
import Modal from "reactjs-popup";

import ClipLoader from 'react-spinners/ClipLoader';
import { GlobalSettingsDB } from '../../api/tasks.js';

import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
```

After:
```
import {withTracker} from 'meteor/react-meteor-data';
import React, {Component} from 'react';
import {Button} from 'react-bootstrap';
import {CopyToClipboard} from 'react-copy-to-clipboard';
import {render} from 'react-dom';
import ClipLoader from 'react-spinners/ClipLoader';
import ReactTable from 'react-table';
import {Tab, TabList, TabPanel, Tabs} from 'react-tabs';
import Modal from 'reactjs-popup';
```

```
ReferenceError: ReactDOM is not defined
```


Worried there may be other things missing too. Mind having a look?

**Comment by jonocairns** [comment]
> 
> 
> Hi Jono thanks for this. Just having a test of it and there seem to be some issues, for example the plugins and logs tabs won't render as they are missing `import ReactDOM from 'react-dom';`
> 
> E.g. tab_Plugins.jsx before:
> 
> ```
> import React, { Component } from 'react';
> import { withTracker } from 'meteor/react-meteor-data';
> import ReactDOM from 'react-dom';
> import { render } from 'react-dom';
> import ReactTable from "react-table";
> 
> import { CopyToClipboard } from 'react-copy-to-clipboard';
> import { Button } from 'react-bootstrap';
> import Modal from "reactjs-popup";
> 
> import ClipLoader from 'react-spinners/ClipLoader';
> import { GlobalSettingsDB } from '../../api/tasks.js';
> 
> import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
> ```
> 
> After:
> 
> ```
> import {withTracker} from 'meteor/react-meteor-data';
> import React, {Component} from 'react';
> import {Button} from 'react-bootstrap';
> import {CopyToClipboard} from 'react-copy-to-clipboard';
> import {render} from 'react-dom';
> import ClipLoader from 'react-spinners/ClipLoader';
> import ReactTable from 'react-table';
> import {Tab, TabList, TabPanel, Tabs} from 'react-tabs';
> import Modal from 'reactjs-popup';
> ```
> 
> ```
> ReferenceError: ReactDOM is not defined
> ```
> 
> Worried there may be other things missing too. Mind having a look?

Sorry about that @HaveAGitGat , should be fixed now

**Comment by jonocairns** [comment]
Added an error boundary to give us a bit better console information when an issue occurs -> https://reactjs.org/docs/error-boundaries.html

**Comment by HaveAGitGat** [comment]
Thanks!

**Comment by HaveAGitGat** [comment]
`Fixes some missing react key issues (https://reactjs.org/docs/lists-and-keys.html#keys) (we should probably make this a bit better than what I've done, but it's a start)`

And yeah been lazy on those as it hasn't affected anything (yet) but will sort them out.

**Comment by HaveAGitGat** [comment]
Hmmm transcode/health check workers weren't showing up so reverted the changes (and 2 subsequent commits which have been re-added).

There wasn't an error as to why the workers weren't showing up. Need to fix some buttons but will look at this afterwards.

**Comment by jonocairns** [comment]
> 
> 
> Hmmm transcode/health check workers weren't showing up so reverted the changes (and 2 subsequent commits which have been re-added).
> 
> There wasn't an error as to why the workers weren't showing up. Need to fix some buttons but will look at this afterwards.

Ah OK, I might just slim this change down and make the eslint target specific files first. Will make testing a lot easier

**Comment by HaveAGitGat** [comment]
Sounds good. You’re right about doing it as early in a project as possible haha

**Pull request merged**
